apiVersion: v2
name: alloy
description: Grafana Alloy - OpenTelemetry collector for logs and metrics
type: application
version: 1.0.12
appVersion: "v1.5.0"
maintainers:
  - name: homelab

dependencies:
  - name: alloy
    version: 1.8.2
    repository: https://grafana.github.io/helm-charts
