---
namespace: default

ollama:
  ollama:
    models:
      pull:
        - llama3.2:3b
      run:
        - llama3.2:3b

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 3000m
      memory: 4Gi

  extraEnv:
    - name: OLLAMA_NUM_PARALLEL
      value: "1"
    - name: OLLAMA_MAX_LOADED_MODELS
      value: "1"
    - name: OLLAMA_NUM_THREAD
      value: "4"
    - name: OLLAMA_CONTEXT_LENGTH
      value: "2048"

  persistentVolume:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - pi5-01
                  - pi5-02
