namespace: default

image:
  repository: valkey/valkey
  tag: "9.1.0-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi

persistence:
  enabled: true
  storageClass: local-path
  size: 2Gi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi5-01

service:
  type: ClusterIP
  port: 6379
