{{- if and .Values.agent.enabled (ne .Values.agent.deploymentType "PerNode") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beszel.fullname" . }}-agent-secrets
  labels:
    app: {{ include "beszel.name" . }}
    component: agent
type: Opaque
stringData:
  KEY: {{ .Values.agent.auth.key | quote }}
  TOKEN: {{ .Values.agent.auth.token | quote }}
{{- end }}
