{{- if .Values.hub.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beszel.fullname" . }}
  labels:
    app: {{ include "beszel.name" . }}
    component: hub
  {{- with .Values.hub.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if .Values.hub.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.hub.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "beszel.name" . }}
    component: hub
{{- end }}
