---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-agent-pi4-02-secrets
  namespace: default
spec:
  encryptedData:
    KEY: AgBSgOwchj8+cLmScYL1fjE65w2vKbbXTvifMo3cXOSJu35G8+uDSNvfcRLRtRnIQTr2iQd00wdOptErvvDsiejQVyPLjdmr2cuRO3TtKBX1HEWZD6GHsk5DrWmLlYxiLrsJBSmLPsIxsz9tB6HjynJxo8eZMLAgwqRN8Fj7dSx2Q9ohRYxUPxr+2ruBecruRVxLfwUAyplFPqKOmk6U70DaCtgPBLbwA1C2UCY8Abp1vzbHXncc3B7oOk6gNdnh+VHe6+zpWAf6VoNkeiNhX0mdowt9LpziKdFk6JCJiD8e+loa5Fi7rtdOtnEhyBEWCmntCVZFqtsyTL9vjYlHimLGfnuYjM232xkrXZDhUPC/Ou0XSi1xGGaq4TG6RbtheF+sTjGTfIjWWg6Au2nh+2bqru81rPbF6xqGpmITq2+V867//EiqHBj8DWjJPujRrMzda3p7PLsDuMSkQW3UzB6LbAWnKIix9rXhaYV0aGKcfQD6Kt3+4w/B9cbaNCIEi7/eqZtK6BYIwkIwBIeUAYVJ7dtXBpjv6roxExP0vM/dbZWrymIhKpmDPgDfJEdLWL8LoEY1xRjU1qEBwa9a6Lb8UY5LoIU/H+Yo8D/KBo6P8ah03H959G2S/rlLeFFOD0+OFQ6+FjAQ+sJ4Ok31jHESQj/QT27EMKRW0tJFMXQ3mNSahFQ2pSu0Mt4y2nm5qz71N3N24VIqZmmavrph+wBgJDXVLTCr1gDDZrIbFp2R17FX7T546u0r+ynFA9SMPACXflliLe/yOJiz5KSBB4PtvnPUYjKawFHv/NX1t9K+ww==
    TOKEN: AgAsL/MJrUr3VcghAisVywAEZYu3l5LSVDaKvYnUhONoez0cTC3mNCzN52A4JUBJcQjzR8XezJez5+yFEN/3wOfb0dU3z8iZf6GkUKr8dqVYsj8xQ3l9oKcf5tSRvGqntTFOQixJKmzOclpsK4yhWVFjy5789kwqkBX8msgSz/Oa5LhT597ZYuIHvAye+sqsk6vlWpILi0R+3F55CcntGEU5CM7U8Z5OHzHnO7ZINtU0f230DksRMQyiva2YaPrz+KRf3ibYAxABacjw5Iu34GE3mZbdkPH1F7ap0CXW95qXcacx2wJq/aWrR9MFRygm76qlu596m32GyC6Mx3qPiyEGia5jdjQRn8msfSoTmRMARPbAYn+cOewyaCbKHwDItL0NJAbCTms5EFtOM+aNwTvptxA3ClQQwjCA3bkrKwkOqKTWNiZDediBXWWCBBXVshkZ/JNQQkzCaiOpYbBdZTVo5vc3R4BpWkS6Wcc8qUPhE2cWKLn9vTAH9cm5mNxUJTbScthW2KV5YrxPvsvJ/pefTRs7Qgot0YCpyzLKYJUTOu9LRHzVkvxmG1J8C4ilKzuledOIFuDTFhlVVChtbUxK8rJ2WyVXvON6Hr3nDisKO/FfbmhtRpwiZRx0VdKuVum0BMvvLi0XRpBwTdwNU2pYX+aWF/TcmqodZUY8gpPOmQnC5rowV3rlA6nqw/alBmzPhIopHv5XkpMhp8UY8w7L6CyCpnZZpRJhmhRIWqV6Vv1H/hs=
  template:
    metadata:
      name: beszel-agent-pi4-02-secrets
      namespace: default
    type: Opaque
