{{- range .Values.velero.configuration.backupStorageLocation }}
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: velero
spec:
  provider: {{ .provider }}
  objectStorage:
    bucket: {{ .bucket }}
  config:
{{ toYaml .config | indent 4 }}
  credential:
    name: {{ $.Values.velero.credentials.existingSecret }}
    key: cloud
{{- end }}
