apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: {{ .Values.namespace }}
  labels:
    app: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.velero.serviceAccount.server.name }}
      restartPolicy: Always
      {{- if .Values.velero.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.velero.nodeSelector | indent 8 }}
      {{- end }}
      initContainers:
{{- range .Values.velero.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          volumeMounts:
{{ toYaml .volumeMounts | indent 12 }}
{{- end }}
      containers:
        - name: velero
          image: {{ .Values.velero.image.repository }}:{{ .Values.velero.image.tag }}
          imagePullPolicy: {{ .Values.velero.image.pullPolicy }}
          command:
            - /velero
          args:
            - server
            - --uploader-type=kopia
          ports:
            - name: metrics
              containerPort: 8085
          resources:
{{ toYaml .Values.velero.resources | indent 12 }}
          env:
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LD_LIBRARY_PATH
              value: /plugins
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
            - name: cloud-credentials
              mountPath: /credentials
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
        - name: cloud-credentials
          secret:
            secretName: {{ .Values.velero.credentials.existingSecret }}
