replicaCount: 1

image:
  repository: amir20/dozzle
  tag: "v8.11.0"
  pullPolicy: IfNotPresent

# Resource limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"

# Service configuration
service:
  type: ClusterIP # Changed to ClusterIP when using ingress
  port: 8080
  # Uncomment for direct LoadBalancer access (without ingress)
  # type: LoadBalancer
  # loadBalancerIP: 10.0.0.204

# Ingress configuration for HTTPS access via dozzle.home
ingress:
  enabled: true
  className: nginx
  host: dozzle.home
  tlsSecretName: wildcard-home-tls
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Dozzle configuration
config:
  # Kubernetes mode (required)
  mode: k8s

  # Optional: Filter by namespace(s)
  # Leave empty to monitor all namespaces
  # Single namespace: "default"
  # Multiple namespaces: "default,kube-system,monitoring"
  namespace: ""

  # Optional: Filter by pod labels
  # Example: "app=nginx" or "env=prod"
  filter: ""

  # Authentication
  auth:
    enabled: false
    # Username for authentication (only simple auth supported in k8s mode)
    username: "admin"
    # Password - should be overridden with sealed-secret in production
    password: "changeme"

  # Timezone
  timezone: "America/New_York"

# RBAC configuration
rbac:
  create: true
  # ServiceAccount name
  serviceAccountName: dozzle

# Node selector for scheduling
nodeSelector: {}

# Tolerations for pod scheduling
tolerations: []

# Affinity rules
affinity: {}
