{{- /*
Immich Secrets - Fallback Plain Secret
*/ -}}
{{- if or .Values.secrets.DB_PASSWORD .Values.secrets.JWT_SECRET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-secrets
  labels:
    app: {{ include "immich.name" . }}
  annotations:
    immich/secret-type: "fallback"
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
{{- end }}
