---
apiVersion: v2
name: recipe-rip
description: Recipe management app (wrapper chart)
type: application
version: 0.2.5
appVersion: "0.1.0"
maintainers:
  - name: homelab
dependencies:
  - name: recipe-rip
    version: "1.0.34"
    repository: "oci://ghcr.io/jcserv/charts"
