---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAHWBMzocM5OwcFp9MelLH/y7z9cWvdi2n6YKESGKKAlCQ4ugVmr6R5+q4aDBU1qjllFlUuACm2htsRqON2bgmOLsdmPRGsDPI8u4wm/DghgvwQq83nRMg5ZyigcsPt9QZKTKTLWiTTbfOeX6dSELx/CZaQ8bNmIqNryzCJ/15xjYVZyC56rD8tJngTtrUi+JmKQG5RdUgcD/7rTh3v/YcNxMJ+6V4duvzDiZQbnw8CyTghUraPs0IXuG325uHLpG0fNNS6qLVJUaYMZBcYxPszu0orU7aJUCTWHWDHqx00BYqXHVuIZgmWJT7l3fJdJWSiPI7nWeUKSMuOR/4z9OmlpLzw//Xr2rDFOHUlNNE2CLiUhO10TneJNp1r+JC9fFDTjJKFJO+kf1aeWQHTm5ypWwdCbG0GSL1KUNLMatOTvZhzOan8Q7cKoiyxtVUqrBZMX0XF3pJA7LudFcQJLGfxM1koyKiSzXJFkHj6fFvDDvWDezjf6ZkAaS89UJlI+QWeH+ZVvsX89yx3TYHPmudObYYqJMh1VevvnlL77K/i91VGgdUqw9f487o3cimkjbkUSUA8VDQCEd/UnbsQUZtRKCzePS1Y5humH9zQZpawVVJynj7RxGi9g4ZV4Dka+fJMbjpX/YK84qS+V00JW8vyHZEDg9BiWx0Mwvx8u2WljpNrChWzIHmdYnNnBWfKo0npB4QX9DS6UIwO8jmA7IGUfe7C74xwFI5TxpGU8y+6sclh9yyw04RlJTffUA0=
    JWT_SECRET: AgAzc+5a/0UsUUylbjppBJREmLa6xnBGMP1oHfewNC/OWBRd99LqJGGLftdGWVWho3Aq2lQNTqghmomH/9TXK2d511CKB1T34SYBxaXafRnDqSTCHfr2IWLS38OiKZMJHyyvIeZqdjAwxUiA9Owf3f9rMOIqJDkmxhdlQtEdZQHTUNnW+R9hESuwmeGEthoGIyYKSCW+n5Ld24whVMkGkKEP7Op/ayiOqXDETi2NYC2rv9WSNC+MyxZ3LPzjkjrjLdI0E0vl/EWG9Vd09VU4/LTcUYrWYusmijYrb+XJ84xUGCP1fVNDNMhP3b3NMGw6avYLMhaz9QxT2lt9qsqur7rcelTJnfGTIXhRiqRGLRRdxvpTdXBNS7VwThjgNKQScws5LW9op8KtG2A/r5Xre3IMJIeuaFwgJdPdGai0ybzFasUW1lAfItmxT8tgjKmZsmeeJBgoSqv2a6QWYvgtfq02WhhUx+3xaLMlwp1b2vpllB12e+YYAN4gQKy29Z2bk8yz8GAxuGmvIOYXf58aSSyNqICaRJ3J3HGiMjP9mIxGSbK6A+o6d3M9KJ/lmzIenw73fGKwv3BQl83BkRK7+l/IsC2VDsvlLzC+UpWE5cL58P3VphKRzb96yo2xa8DHwYiHG9MsgFCFdgB2QhoBWAzJ0eei1MQzla+9JTqj1aYLIg0Hs9cOwrfePKvdyi2T+wHh3+patLFvlqO4WyG5aGaeznB2FSGmEbfbgYb597H/l60DMuVKDrrY0HlKdnU=
  template:
    metadata:
      name: immich-secrets
      namespace: default
