---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: default
spec:
  encryptedData:
    cloud: AgB/D3uPab+h06Qj7bWdDqg6FJ8gY5E+cLptDjE1bgZRnRl4HNcwLhzVpPFW0JdxC/AW079XzBN0tlOqBiHXE/4/nvZoz2DwpaBY/0QfPrbbHNvSYtu5R55TZndJSv5lhaukYxwFJzZcWqJrO1wijSqHdBnTvK6d2z7zEuBbupq88WvKbA0wsXvIOOcERMA6OeMuGdYFjg+4cHLQ93Di8iOZqqEebkgNZocYh+ngvLAThOSpQF30a0ZIrPZe3Rw1YSZmS7hLJZWrpMtlUBFz7RpJvxtwcpnW1XoXCksijCIknf8Vf+qXCpe6cnnjj9tLvsBpy4cXeZubjtOyCZD5pjBpyikNrk58meCcvII/rU4ccYkoYrKjnZ9uvOP99Yhg+0xUoKjf1D8q1Lgm/gbBd0PXxNfSP+3hKEywULnlhCrMpve1l7eC7h9j5frhKI1zNBGiOzlbjXqEHvWDAheSf2lKZb8cuBQhyYVIi/Z8pfNgvvc+hGZ09pVlCKHgCqLcJJobAfhzfmvE9BxO+NbnKFzfere3C55P66KqpRA9zhnt1mJyGu9v2Gx6ta2BKBQl2Xp+wA9ZPcDDYvPkGb8NdyRVhnCrs97zTWWwl4kSTh0DpxEkX3rhEzigeb7r/CsYKyoSEgxrciC7elS3eNZFuiYoJo/bF4hmOKqpymFk6TlNwthIij5PO3tajHVrD0lWiv+TQVpU/V9TKZzoxSVzDlz4FUmNllXOHFp7E891CdA2AUY6fzLQZ9jQFkZJfizlOCKzpzMtZ+AO6VTodD1tdiandf7GJLJ7lWCf+HWKdzdOEL3NADXeFFgScojQQ5T1XpBrJLixtYnZ/JL93Keeo90mGHsh
  template:
    metadata:
      name: velero-b2-credentials
      namespace: default
