apiVersion: v1
kind: Service
metadata:
  name: authentik-outpost
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: authentik-outpost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: outpost
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9443
      targetPort: https
      protocol: TCP
      name: https
    - port: 9300
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: authentik-outpost
    app.kubernetes.io/instance: {{ .Release.Name }}
