{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
