apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.media.storageClass }}
  resources:
    requests:
      storage: {{ .Values.media.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-templates
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.templates.storageClass }}
  resources:
    requests:
      storage: {{ .Values.templates.size }}
