apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infisical-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infisical-pg.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.size }}
