---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCWSSbUxnXuDgJv1h3A1LhGQbbJ7z+64uh5YyeWulcn9EJfBJxVsWQHmfgV1kSFSMf1aU9G/GscrkI1DVHgQCulLnapD4dp2pEUuzB2BRSKcaww90E3sjG3gecseip5Bwy7rh/+x4ZZYqlHk99uz58piIQ7+chY2bRcHGPPcL7En2lV7UETDIBm1niJxTs/l109qoelcs/aGBZKmtfLuU+GouKvOatS4vgJJSWahIn9XJV1N4kdTd+qeME2j++KDCfwTXEQWQHl3rakSZDwvVWEC5muzSO5lPsWs8V7O/fEbFVaoE9YM5QbHNBHzrs2mhhtrk6i4XTbXi2iyQKkzs8mir3fWuPWvQIlu/DZz8tGNzIZsyvNZ5Hvv/4IkGJIRJPOnnqXxseaK94dFTJJHqRdGEjp5W7Y7qaUhpMX15R5vV5PUfhhL1kVQiaKMRYDdLa0xddk9LmqkHkhvI7pRQ+kc7sgZ/1WgTOyr8AEWkJT/M0Zbm/eCKlSpyqgMxLaZCzb7RCv6GAnrACneh38B3Xq37TAv9Fc+O/2894JHSHbabqBm6YgjwYi434CbEGZuKKoNvRu7b4ScLj0rIkFjFoWOYkCZDX3xpJVvPxjq8P4u228LvlInFVMnKtz3akpnkh4GWj+9CPlOwf8owlkf/392ezoOK+W2ltpmPjCHLHRHXz89tgZVly/R0wVu2egaYLhyp6C3a8PASgiiSZLL2s=
    admin-user: AgCAUh29K7hfUMVZnQJ1pEShWS3o2ANub+IJZuSJdmoF/D5j8zJFuQql9Cz4y9aSpimQd02dahJvhQ9oyUKpNxfNbnsfEm8DapkkiZ1Lr8FA/7Emy1cx1nvmO9iGfE2ArsT+LMaw0lGSiXKuQFM6h10tHBW7ypuH3fa08WKE75zMGIkJ26GmrEgO2QtD8y9vo9IQHR24ucx/5fjifxyL84RJxSxLD7QTD36Q4MCg9iglBBH9AihuF2STEv6Y2HY1M6xdudkUYxkITY7UIYu7IdcEHVgYX6OgyNeBL8ZPBINa9rSMKsTP17cHquc0fjVN5Yu1eeRgMA/SaIATK1XL2Lgda39a2W+6O5oiclRduUQwfn7K/GxAV2MnOQRw32wiYVo/w5JgSgBiYyFI5VwXYIIb/GfGoD1qsQGDkT1z4jZHgj+/jDQ/wwPTdkMWqF7Y/MPp7Y74OT4skZigF394vLndSwY9+Q66aXXXoLpTu5DafquEbJGF8s3Yb5uM5sW8tpbR2QtWSsZyBVkzqSI3A6gd6Vj8GAi68v7awHtwgrgtLI61A8v7LI3NZPSE6yABDi5gMKaiqz/Wq8povdG9NlGNDF8S44WFhl6CclmbzyDY/3VRSS4McqwR8tAfUbsq8Xvy5/g5ehvMhts1pVGeqSW4/LfofSqIPht8WKd2OdIpvOI3QX5j0hv49EMUCEprN9yBOl/fbA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
