---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgALkgIMCzoVYmFY+VM09WgQCXkaonbC6+RhyMV4AdOwFE42dpnlS5dx/7XGQYxGV705WJO3Iz07GrYL3npvVHFjX1dEF0RF4Kre1fEfBfpFdwMG0OwAxAvOQh7HlMAUQS5rUwOE8LWRL6+TpwLdCTwtTR0FlhxWiIXCeS3dhqpjS27eyUl/QhNFWgCoUI+Y1yye7/jNAsYNS0FuKqHjK9t901PgfUXqpFBYAP0JxnHP/QTdRHhLvQgc90XtNs3iDdPSgMBkiJ/fad4uUO+Gh8aZJRtmwD1260QVtvp0tvMmIHUjkgXSPoX7Prb7kmnVMo49dK1X0wlTiEbIgK24XznCWkGXZAXci3LuEyAdzBIDciCAkYAo1VtCCHgU8SPQzEkRq3NRZrR+CLKKtTQjDTw34l3CbQ+Dr9RF25Fi3OFFI2GHzCC6Apal96z+viLlhhoAJQsi4lqq/dsz1ES0t2/rmtHKGfDKF3hXCApwkEpWCSsfHu5S+fQ2zG04m9Dg9NOMZWzK3knbx5aJzGLkgvsvSmkHyM6HK7h/Sxh4ka2n5Wf76S13eH/4IINV4fwm2U0nQiM3oilHl4V55bVoJBV+sZ3+M5Q5ppfshlCpAXELmWn0o4g4zWrC/DSYs2uLHFEQAqKv3C+/G9pVVq86mN6Q8cI9nbG2uZXjHoaEA6WWK9t5FnUvF/obT9fHXQgK5D5f3rIG+vSY6nQE463ubmg=
    admin-user: AgBPFFyj2L6YlwrL+odS8sO1pZyd4f/KN4szgmfyh26ierg1JhE6bNzFGE/T9zeULup1IeXQTjrTqskNtwaDlitqfM/qFX8Qn4R7qdNglWVo/MOhgqufvgnk5z4NyoBAsHDUmfztLlkd8wyCgbm8OnijSj4g1PCO/QldKxeGVzbudyyUx80ZlPpfYTdZIpClJIFmZiZl6aBze1xIm9Y92Wr5jO/Qu/rX+9A5kf2DJZ57dhi2FYwvQBuo4S0IFtT2zh070zGijZELCiG22lcF/s51uK82u0UN0cnnvhO93kJoYBLuPYhW3rIDlAQTLJyoCxSd28oCvRaHvpqDn8aEndMWaBzNTB9TnsIHx7Zroc8ddgMl/QIYIxDWnnI3Vee5v8iWq4goV0xDlTEND3U7UmZYI4vhsb24t7oUDzM55HDVbSLAQqQHMFDJAohs106o070fXZob1NvMHvDqPe9o30hjIEYQalW1su5HN72jB42jVKR67C6/rXhkV4eSuOrrfROGjERizm9cumxx7EQxNRvf2K7WbEQWHgLe0JmSeHtFnvuvJq6AVCAxVd9VMTBw9ngRL6/iusVOcroHFVkbWkLvBRc0ujDjJhgj/Si5mXe7ZSMxCYqG07lNTUYr5a/iWyFsIn0nghNQamjYfmZpczF6m7u74+jttI7loQcxIKXbM8fjy67BRWpXrngWlEs9zTEQPCZKeQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
