---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDCr0zIFp8nAwysnn9Bt1XzlPUxOjxSJb6ELHwjVnujkHd2NrU+IcmTM+bshwlTk+r97Hk66t6ISKbi+W5ca4Lu7pGqUNGbTTfHo5CLdmS28UI9Locv9SyOfoznx+/HkPxUyNCDANTHHJcXMa7AqcC4TV4FiCW4OhPzv4QrHOKx1qtzdimZsYbFIgKmJJKRYiRVbNOMQuwnZsd6fHhFm5HSDH1GyUDNQI4IZ1RcuYrzst6y1gD0fLzDW1HV0F/4WjQTdTjha8VLoKycDWOUf8ujipb2fRU/OxwdoF0UVPXN5zEPdPiglLu7VIY8VMahmSAl6/U6YMpOfy3GI0MTlDlquZw5Y8rqjTqD0YvWqaIyZ3t5VPL0dZ0rs+wNasQ3HUIwJ4Cb9XjrtsFqfjz/taDsX0MrdvocQmlEpT21PimebdFiWnH2khGE5Vb6uHRVvA/Yh4fH9QMEQpnqADdsrSa3pM5wYtvGzDNyxncD0L1LyfTfkMsteuJI/4/gC2jRvn8X9C16o6kFYnJsCubkRyD71TfodiNj/j675YdyRfHgLEOJeuqa+hdFDL8YLE0y7LvjWaTcKEl76jINHM67F0Aq7SH0RzCoMacvW/xLW+S4G/R+eh1Xdypy7jeuDpYl7gt8FMI0S6e0AS05IjWBdCuH1yocdAZQDaCLiwD2IQyqmEmBZxZ/7C1CpBl9cACx99KZoB+fYwpoaX/344peSIWLvFzDnpeOXSaP8nlZGpb32DEnfcA73k14
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
