apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meilisearch.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "meilisearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meilisearch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: meilisearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7700
              protocol: TCP
          env:
            - name: MEILI_ENV
              value: production
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.key }}
          volumeMounts:
            - name: meilidata
              mountPath: /meili_data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: meilidata
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "meilisearch.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
