nfs:
  server: 10.0.0.28  # pi5-01
  path: /mnt/hd1

storageClass:
  name: nfs-client
  defaultClass: false
  reclaimPolicy: Retain
  archiveOnDelete: true  # Moves deleted PVCs to "archived-" folder instead of deleting

# Resource limits for the provisioner pod
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Pod topology spread for balanced distribution across nodes
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: nfs-subdir-external-provisioner
