version: "3.8"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.netclass.ignored-devices=^(veth.*|br.*|docker.*|virbr.*|lo)$$"
      - "--collector.netdev.device-exclude=^(veth.*|br.*|docker.*|virbr.*|lo)$$"
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - TZ=America/Toronto
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
