---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: default
spec:
  encryptedData:
    WEBPASSWORD: AgB7cQpHgT2UcS8ucL0OxKiPXp3jCauQgbkcsvZxR0O1yW9YEfoCA/Bk6FHEnBvDwZsbGp/wjvngRmFvgLQfynsEKttQZFxxZCh4pZ/s+TCjDwkAdPmYbs6okLgkAHDOX4CY/lDw5ZvZFx/zWELkBqArqlhrekdQ2uNXospO8g/DjPmxCkOeW+twAScxO3QWRE43K4JYccp/60YzleI/Yvg1hcaX2EXswcXqdMyipR63tMejdkiJO6z3a9aW+pvNXrW9qNByXJyag08uKNozKPG8pS1Iff2d6wsaIXHgkmOrN39SVGg8ga0OC/Nh1MemEmzXOPIq9C6mjykyUXZlZRtjJP/NIeSqI+3VM4krZHGSliYbwOjXZBYpIEuUQ+seceVJjlJ6Mo53uWaG6v/U3soUF1gxns4BwGVIU0RDvA0u5xm7EZNseogO0WTpFzKqBHVmpNSEAuTDNLd0MZl2/hjZtfbrtufYHQsuojLoyovsjnwHJeLYKaar1oTyVfiKwrW8yDLOhezrj+Pcc6sH3J7Rsd5O7NrgqLSJa0NMGg0+EUwQ2uZ6g5ZsruaFioIxdQI03KhmGrdgjBtZj0zt1SpxqRbeRVBqqCUaovGVvvBuS0PJmQ6ZJv92fSBRdis98InKoyvoeWAj6ITtkIRXTsM1qkSyAyCyMJ6cD0m+qvlgsYZG8CmqRfsUpF74ce9GYZWtQWa6NsHAak8wT+tA2/k=
  template:
    metadata:
      name: pihole-secrets
      namespace: default
