---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-custom-blocklist
  namespace: default
spec:
  encryptedData:
    pihole-blocklist.txt: AgAyzQdZDlRl7qqNevfknuTcj9F8gZy89rQhmoic0JABlxT80NgcLpdpJOt1t4O5pEPZL2RktrV0YBpXSUgEt22VgPF1wXJjlXhSOisRfUE+c0YVJtW+KLxDUnvyESqYDodHSmBI3AKDaF3UxMNUAfPMUxafAEJ3Kvc98Bvjy2/b7oV6Ypy7oQV6NzslsJ81CDsnTVL7NCJyNFdmYnftInaFwoYW9CpFO0mh3qsdrbhHKzLhZHfsEjo6GctRW2sERc2qD92GUFaAoyiDzrE/RFNMc0/txDgfsJeyuLomIKkdoO4zbn1pR1K0kVaKOkPLNUJ0R1GR8C3KDzATr3PBI68DpxFl9q3o+PkvciNHR1MiBsgVGjPQhFUfmdP8q84CAgHjF8U2FJmqRyqHcGOBQVXORcZb37iRUoxPAyZxey/tsxgZSolrbds+SQTA/ZbktjUqlo3VQvQRnQmA+yVZPr9xbkkxfkHMTuyyf01NPfl+ecvY+NYoyy60u5AGWe2OIHvPI55o8rXkngeDVEjAN83ZMxq9xhA3Fzhx/GpJ3b2KQIYMLljUDliCHfyRflaEvcf2QzGDYfz1C34ZbJqKi6pCYMOTX3Awl0NXyDC12YWepAu2emkUeRxAFPsMVnXFqWPLQgMar4TjdGSJxnH5Wuzn2xi09DLiM9GwTGKgCrnSe1CChYyY2r/vVbNOK2mK6t5rIkyA/8h4XY1mxGqcvTdDsmkqDLVVXBKJv/wVZQNIzLwMunvG4Ai4iI8VppgD+fQOsRZwWRraX+X3KQUCDJ5P/yzewrtQWK8Ci61Du0+xTyApqjCCmNSwbrWl/YM+ZzhEBkQytZ7nv+LvM9cIkS6D+7tBMFIqscmyI6d+KvLy7UsmD1cdpJAYSba/aJWZTg46r/C4kMnEKjrWT9JfNTIx
  template:
    metadata:
      name: pihole-custom-blocklist
      namespace: default
