---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secrets
  namespace: default
spec:
  encryptedData:
    WEBPASSWORD: AgBKB10PUakrT9xX099PngZSZ8hr1eoYeaLnsitUDV7WVZIbMrAvWhb5klva8ZNxIfISE04q9YC4Vo+wWFuBxg61knZM/j1xhisbbEjTj66owetNU7yxSfC6dIwCZ2t5q+EMyf0ht9/yIQuOBW52kWzUHk158N3k4gTzs5uMT9ffgAChm9v+FxOgWkDX6BTX/lPxxMoIe+mFxOUsWa45j9nb/qPhRfNQbYaLmBRLGB1qpuPJcWIJrXCA3UTiQTKAjlJJY+DeDNlI5EK2wSk715yA2k8DtX2I4eEPHB0hkYpd3LWYPGjNTDp9yX5R0TiromP7eVZQuWieJax09k3j55WL73TPHufyu0/OluTCTqYhcfvWc5qS9qESJDHKfji5K1yd90S3RtYdpfboWuFInfkta5skm19dIxcKfZ7pdSlYcCmYFbxkFK3XbtKOGscOd6qtB5/vRE/3ltRjJfscBoN8O8rMJR0m1R8/STObbE9+pflWJBqw2xaG95XAxGg6MtyrCA3GCdnOKPCqExMy4Wk2GCKORoXM+wV+rF4cNkY6AGAt1D7ZpX5zgzymktbCKXFFVCk29p9WQf4SWqWW2N9YAU+SgeX8lxoRo0mPkOvUcFcaBqM5jEqEghoYDpUJqFpL9SAiHrpllZmDgN+BPw8O7R2PqhCad0P3w63rIwLGPiqQuMZc2/i0OMRtNyTId/rVGKwPTwqpJB2TYHjhLqA=
  template:
    metadata:
      name: pihole-secrets
      namespace: default
