---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-nebula-sync
  namespace: default
spec:
  encryptedData:
    PRIMARY: AgB27FQLXJ7sLJm6+d/YusqdZLP8bp5yaxLWCHuBlhyqswxhcKAOItSRzFLZUHtvBT6Wq+HHFUKQtp4hJCxTfu1vSgirJugziPXOpe2aBw5PQ/q/EVvadTic/6pQRr2V4imn6SO/vshrQm0x9Tpvj+DDKrIKT3guIA7b+rbFxh0WRmi4CTg7Mm66zX4dvF6a0n0uAFTL++XRnAXcxDmxavrdZo/xYIQt0mrOgYLk7PRQ/Bug6ue0xzkxIb+T23+fN6QXPZngWI1YlKOT9py6BgUVKm98Ii6EN49WQjhaHyzCfb3SDFVRAr38V+LE7/+luDrHdt3c/qWEXBtKXxFGvfL8TFMfgaxSUu146LVUMt4aXcpXkuxV1yQq8qFaTDQW6yGSDUE6Z3+rYMfYRSzGw4kRPvXRWGv0r13Gr8U3qzBUx/q8DsrJ6uqUuHNd/JUSkr4Js2ECuPWJ1x5fIjb0tuxwsOXSd1dcBEScbmoAnQzxBVIK/ivF2smiOAwe5IaQ+4RtwdJLlqBd+sItiUw5Fod6SzfZBii8+gLnnmynBDkdnCBy5kJ/V2Wgy5CtWw03ErmsLqFXIqfgl3uoDWUCwp+spTcGHWX/M2Cz4K/gxhxCt4JnEiAzFTBv+msK7ju6ANLV99UHSyOoFbWqorpIQ3l51BbUgb0tMA2eUPxVAjHU+f2YKByIuim5XaY5NNgwopBneUMZTVBc2/fvadTTvjLavJpYNIvcVZlqqCxg9GDQCqaB22vImDR589jMByNpPWskSg==
    REPLICAS: AgCNrOSRshxi0Jv7195UYNfdCeCvUE1TZI05TvZixB7bYR4Jyf9NvUC0bdmvj9dc/lw+O4ATVmjuCS4QuSzTfjYhKJzZSpa2mkdBHbgLWJqLvVgZpHSji8uAqQG0P6wwpnOTii3hJl2DVQHMbqwg9H2nOTHgwlYw1miK13nmOMiAhs4zBhUaaybqKEx/7Zqqk/TWQkLGo2Ix88HE+j0E0i7Bt/huflvrpHVe/jqahCVUOX6e68YhCzqvC8lAYLWeSnil/P5QG/a7M1fpnsCXPsC3spHc4NiqptZNCOhxD4iJ7mvRlNcZ0R2tmqtfaFq1z/jD4yI+mc6yBT4bUwE4HlF7ibSJr5KaOfdiPudLGM5G9a2mVLsZDuVRYlJg1rx3ksahHqtpfJidOimCD5eKcMNiwtbs211b8RQ/narjemONg+GyTTx0hXQHo+CDt9xTGgGGLmrjAHRuJv2tNnAVdynUcIxLjm/ED/hvo1M9/NnMYDzBp7siAGAzY7yeYeZsMM6UYSS0gEnr77T0kC8TlxfYT5j2qQf1bawS9YwiyvFuLy0Y/GoxKfyc5gsFwn4456sy2+LN5eDT7zqdRqTGiOlXBroeOi8s44UzaWE22nYF7uTcqZQW922wr8VxAokjClv5C4EfFoX1U2q0Oz46xbOGZkCKcsFEREu8G+fe9wFALq9HBfSCOAC/1h3H70i/tZ9oo7tn3V3FOVdyaZeaysb8cEB6PGaCBAI8DAvBQb0sMelfQdd74+2wD+yMbvi+DQ4lRw==
  template:
    metadata:
      name: pihole-nebula-sync
      namespace: default
    type: Opaque
