---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-backup-secrets
  namespace: default
spec:
  encryptedData:
    HA_API_TOKEN: AgCvWf5jYtA/oEXE5TXgPSw8V0L13NpRy/kGiystMzxUpQbH2lZDLwMIFGKInCk5JZ5M2usRkwpcAL1L+mk/r/CbuJKwxL8RzlXxim+s2Bjh5Ku19uOQfl+PcbgDKsCPlzGOcmX3mniU3XA5e43NViw4rJeFSU/rffNsXbXusWB+hGgs172OqDxjGNDwsEzj99sZf+QfWMOguVsu4MFo77vYZCxPiEofsgNqEWEVJT2MH3R/xfwQrCTWWaqzK8GcRN+sQa4fUIz6tAJ3o3nH5avLaTV/VCTjU/XbZxstkTawpAyn7XHwslzi9hS1KBr2LhCZJ+SVzoL4PC4BRqDshYab79NefDOet/kZLh2amwQEtUitTwmAhZwSklBLCVogsvj2hIBg0aVV1aMEYs55wyXNokJkRom3gtjpUgK6gwrBmngdExu0NNxCd7hTZSD92o82FvM7Ey679rqr5yKnr9fJhdSGEmLAJYvxZbVumSiEb/piL3jdObRunAmtEfHQT8LiCpu/EtzviWctMJ8P9MJo2TU6hr2U9ZmMytWY+7C6XNnJotjVWNzVgaopb4629FQo3tE+YUbZfsPOEdVx/cUjuwwqZ+wXdCIZsXZxQ59NyqPjmhbiZrwIVST3aLYAAUNFCHuAecFswPtglhHyZrpsA0TQoj6mZIBSr4BFdSNnONrRnNyhHMDDYV6Dy2QGaLzuNDTU6RyFUBAmhuH6h9EtELdFLaHG8G/HkaRAYkLyuCIhLcID5oK7xl4SvDPlo6T7WD132B8IxXwUi3/DkzueH8HqnIu/pEY2A7C/hp/8LD0FbQt+mxoErZAH7CYJUaAMjOE4bpoBiICTggGUHCwkEF42vZKpET9WAlvSnCTj/bKc4fuANlR9hFopb6wA0gbK9SYQzUDe6xPPZCeZR16gUm/Dg1TdZadjy7k0jXbg+adRIe7aZ8Y=
  template:
    metadata:
      name: homeassistant-backup-secrets
      namespace: default
    type: Opaque
