{{- /*
Restic B2 Secrets - Fallback Plain Secret
*/ -}}
{{- if or .Values.b2.accessKeyId .Values.b2.secretAccessKey .Values.b2.resticPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.b2.existingSecret }}
  labels:
    app: {{ include "restic-backup.name" . }}
  annotations:
    restic-backup/secret-type: "fallback"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.b2.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.b2.secretAccessKey | quote }}
  RESTIC_REPOSITORY: {{ .Values.b2.repository | quote }}
  RESTIC_PASSWORD: {{ .Values.b2.resticPassword | quote }}
{{- end }}
