apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-archiver.fullname" . }}-pgdata
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "open-archiver.labels" . | nindent 4 }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
