---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-backups-b2-secrets
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBRu+xKRst4Zxao3PiohzPqGHKrMS8nKx6fA1u3ne0nfZhP8Aw2wNSE9axc8EXEIwlOQ9vO1bg9hXb6fJSH8zie2lq00oQXf5GMfE2rSO+/VYYokYUVjFmo7zUdcleGXx03YcQTuayuXnv8qDcBQCC055HQaSKhL0iCoULdfMEwkVdrY2oXYEQIjwb6iYMiUl2BP5Tqtaso2zWnumiYDdVeCXOQI9xEaeQB+z83hJtsHgYhCHxU16NVSjfcRXgma0A0H60eu1JQomJsiqb/3o9Gpm+1QX09cJKDwE9HdKsFZ9mucTaWK1fTfjcJPGZ89zfeW/RwVUShpXHgJStCK0vwYNjUuxi0O/v1W4gWxu+Bl0V/prgg947D4K+W235H/u3EfyIzCiXvbI94z9fQTusHszuE5tT6bCagBdLYWH2esalXzQkdKL6rNkqZKgJhfxHvN0sN/fwtefPQtxe1fAPJq2xpEdBA0LTNvXHSCLflJx4ryGE+88DOmYxbLBgJ/lmeOxRhwhs8GsFKUbjMKIKaNEKbF9V6XiImmBGdn15yjQxBK4YAL0dkyQhuAePot9+PcvxecCB3vd6YkxJyMvHewv3QuIeBIkelGQXf2pZujTuD5bon02dWLEQFdHn8XcjVYpLb+MCcaYhc7/eWT0KZgXNrodVu2YBZGcgLAP1tugtqu1S0xVLRqi+OPO7Adg3OEeH3ncemR9JeDQxd8ugUwkJX9i++XlOd
    AWS_SECRET_ACCESS_KEY: AgA1K+Gd4Q4gxggsDVjvYOQD6r4cZ8TZcNuoJ1obwy08aOwSqxsZJupPxs+4LQshHbRWbct44pF2yEPCb9CbdexpNA4mQEtQ2yCXkYJWs7nHlNQT3l0WOyuwzAzWtp0anr9sxG/RwlaBvjyqDFrk9yUO8hgz62FgdjUK2qV6q7YqStg15BqRVGb5yVfhlFURokVEWRx+hlxux1sRHEoWmeYz7LhxZlOIJuybalQfUvwAYjMW9oKH4fEuwaReeLfhl1kgDaI2bYhudPphSySlo1msWc89f7lpm6m9mXCoMQJopqcduZvdQ36Pv+UwdI16dXji9DPXDl6deQqLIL2xYhF/ytSjbjbY5ThnLsICti0o3oMSxKzAa8Kur0ylLcl9GaUAjN4NDtHZOKuUWbFlQZY4PTMtdCK5N2UyO2mBx9TgR+/Evo792Ung+BLs436ap3aEiQISaRb1ymK1kmZfhmPXsM+wYMfA3AG5O7QgK3QybIN5+2FU5Y0aobAw4jBoW9vl1QXtELvm0N/sqimCpN2vStOQWQPnf459Q377r5BNEAf/99m3WAZKHZxKFyVhHy/dzk8bm0d0/znYMqWNnL6G9bTU3xO0lmxwT6GpX050Z6sKW7k+qq3utpad8asCx34zDU+fmldvpXfrErMmLz2VK2x3rmWHZt0n9X45F6GqgIoUxjWNf0C0vE1ldf6uVRknYsfdwPVWugUBuMaoNXqDeXHuImY4d50n+HYcveAd
  template:
    metadata:
      name: app-backups-b2-secrets
      namespace: default
    type: Opaque
