apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-dns
  labels:
    app: {{ include "pihole.name" . }}
data:
  custom.list: |
{{- range .Values.customDnsEntries }}
    {{ . }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-blocklist
  labels:
    app: {{ include "pihole.name" . }}
data:
  pihole-blocklist.txt: |
{{ .Values.customBlocklist | indent 4 }}
