apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-dns
  labels:
    app: {{ include "pihole.name" . }}
data:
  custom.list: |
{{- range .Values.customDnsEntries }}
    {{ . }}
{{- end }}
