apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-dns
  labels:
    app: {{ include "pihole.name" . }}
data:
  custom.list: |
{{- range .Values.customDnsEntries }}
    {{ . }}
{{- end }}
  02-custom-dns.conf: |
    # Load custom DNS entries from custom.list
    addn-hosts=/etc/pihole/custom.list
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}-custom-blocklist
  labels:
    app: {{ include "pihole.name" . }}
data:
  pihole-blocklist.txt: |
{{ .Values.customBlocklist | indent 4 }}
