{{- if .Values.nebulaSync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-nebula-sync
  labels:
    app: {{ include "pihole.name" . }}
type: Opaque
stringData:
  PRIMARY: "http://{{ include "pihole.fullname" . }}-0.{{ include "pihole.fullname" . }}-headless:80|{{ .Values.nebulaSync.primaryPassword }}"
  REPLICAS: "http://{{ include "pihole.fullname" . }}-1.{{ include "pihole.fullname" . }}-headless:80|{{ .Values.nebulaSync.replicaPassword }},http://{{ include "pihole.fullname" . }}-2.{{ include "pihole.fullname" . }}-headless:80|{{ .Values.nebulaSync.replicaPassword }}"
{{- end }}
