{{- /*
Pi-hole Web Admin Password - Fallback Plain Secret
*/ -}}
{{- if .Values.env.WEBPASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-secrets
  labels:
    app: {{ include "pihole.name" . }}
  annotations:
    pihole/secret-type: "fallback"
type: Opaque
stringData:
  WEBPASSWORD: {{ .Values.env.WEBPASSWORD | quote }}
{{- end }}
