apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    app: {{ include "pihole.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.dns.tcp }}
    targetPort: dns-tcp
    protocol: TCP
    name: dns-tcp
  - port: {{ .Values.service.dns.udp }}
    targetPort: dns-udp
    protocol: UDP
    name: dns-udp
  - port: {{ .Values.service.web.http }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "pihole.name" . }}
