apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-config
  labels:
    app: {{ include "home-assistant.name" . }}
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    {{- with .Values.config }}
    {{- if .http }}
    http:
      {{- if .http.use_x_forwarded_for }}
      use_x_forwarded_for: {{ .http.use_x_forwarded_for }}
      {{- end }}
      {{- if .http.trusted_proxies }}
      trusted_proxies:
        {{- range .http.trusted_proxies }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .homeassistant }}
    homeassistant:
      {{- if .homeassistant.external_url }}
      external_url: {{ .homeassistant.external_url }}
      {{- end }}
    {{- end }}
    {{- if .logger }}
    logger:
      {{- if .logger.default }}
      default: {{ .logger.default }}
      {{- end }}
    {{- end }}
    {{- if .openid }}
    {{- if .openid.enabled }}
    openid:
      client_id: !env_var OAUTH_CLIENT_ID
      client_secret: !env_var OAUTH_CLIENT_SECRET
      configure_url: {{ .openid.configure_url | quote }}
      scope: {{ .openid.scope | quote }}
      username_field: {{ .openid.username_field | quote }}
      block_login: {{ .openid.block_login }}
    {{- end }}
    {{- end }}
    {{- end }}
