{{- if .Values.config.openid }}
{{- if .Values.config.openid.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.config.openid.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    client_id: AgBzYPz7A1rPJYqRUnGDT2Q6Ib5G9ycgM06dA1AoeRhpmmJ9u6/8TXKA1OfB+k/fw2Viz3W6uBbV+gO3di4da0whK+N45y7sR+1n4qwwbbCtWelDXYmuvyZc2+GG7mNnmyIlDZyIhJw6U+BcRab9RWUNi+H8fBtIx5FhAtU+gdIWFQkC7a1yWO6koMoGK6OOnJz+rwX/p0AUWtdnVR6zzPKHyzwVdHtu7R69sVUyMlTK6Jn3+JJFfxeJHjisjAfeWeygUZHOzRaGxeQ/d9DbnsgM1bmUrlgJKkAn7ZALW962WUv72T212Aw9Cn7pbVTTy80/reJ6/IAXyvewTyOAHhm+QwA/X8NdN+dkYT5krU1IhI+3JlcewSz5hDV3DubAKNgiLSoRMx7UYgcjkWZm3NBOGXhkZ/kipBs74HBO7U1FvHT9MLV/YUjun1fDR6Vd5RpKZLJDJQOTmAMoYeDcHsG8HCghzImzFxb29kCNtESUgFtH4k0/af8VVbJ5RdW7NyxH9ts0oTJyMMJlXr0XzqphjAgjD4H16nEg8mWrzhn1bB7DU5xPBLlkR21bauKYBPtT3qqD1YlE61w3kyQoJktlzBm7dheileH+xsHaOjxg7FpOKjyd7GH+8GkE5+Bi0pS41yQZTnTRjaPkfsIOXYolIarFXlqKKN+JiTehxgcdJbKBRTtdc4NT6qaQnl26QsmPYjNRAOP4Q9DrAQSXeMWCWdPtpw9bPEr9XZOpUVe9J24SRMsU5RHy
    client_secret: AgAcwI0g0EixCSqOeWN6dHL/GNfTS1bLOW1LN6wpClNSjRdGXOUJA0VjeNC93c8l0xL4IRAFimORtJJFAf1XuMSfvTJ4os5JGtb2ExTV7ez/4OXzecBk/hbyzb4f12/QXnnUmzW/S3QjRI7e0ofP3wtT7KhZaptibVqW4sv1M4P2p9jU9/ZwqS3AMQjk7R0UF2Pwp7NQBPYEclQy0yme2JlI7x26KuJsduF7URig3nYeNTffc0fgMuctZ2SPjgC3HFStnHb6Mkin1ESruerFXi3Q4+DqgeNdqBY7wVmqrF1AuLEjpgGxJ/C4Ez255k6bLz+UJ5FwL/FgA0aMew3X384s10M91C0yKRe7UwoyTfnBrZdwVUjWMoAN7uuEyKQmZ4k3FqOKgL8buhcHIstLFftX1FmjS9Who3cVIHz5NEOByQg73hGeL0+xg9/E+NlnxZXVj84TRZusaJzDv/eks5SsHihvWzOOv60944fIGU2I+uEUJ37s9DC29TMnowEPWgUhT4qcWNx6GyOgTG9zzMw/dx8t6AYsqdAiuPe1D/1U1st1vODcqHZNU/99g7axoimuSUHqAPm7oD87v8Zx0B/LEebfL8lAcIGqnm8aIFv+uoPJI2ohMasTVKSobEdB/XPhKfQ/6kCzeRO+a/QOK3aQ0/ePMaSQ/JMQR90O8OU4nPrbg/WQEFuVwbcB3apd47wvO05vx4shsE8ar7wJ4c9csPvvbCMEHjYodYtynj8T5+dunX72ZSHuy06yrtTXC6xVnn1Yb8I75Ui2iwAa2dSQRH/tHzNjUy1OV9ZQGud7YZm6QoikRpsXBERwDuBT+plRiRVjglT98Pd1r8eUm2KBe/wVpq5/yY3OATab3OG6Fw==
  template:
    metadata:
      name: {{ .Values.config.openid.secretName }}
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}
{{- end }}
