apiVersion: v1
kind: Service
metadata:
  name: {{ include "squid-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "squid-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "squid-proxy.selectorLabels" . | nindent 4 }}
