apiVersion: v2
name: blackbox-exporter
description: Blackbox exporter for synthetic monitoring of services in homelab
type: application
version: 1.0.6
appVersion: "v0.27.0"
maintainers:
  - name: homelab

dependencies:
  - name: prometheus-blackbox-exporter
    version: 11.8.0
    repository: https://prometheus-community.github.io/helm-charts
