apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  addresses:
    {{- toYaml .Values.ipAddressPool.addresses | nindent 4 }}
  autoAssign: {{ .Values.ipAddressPool.autoAssign }}
